# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LWQTLaXIpM73Ft17-OrCXKNUW8UUKZG4
"""

import os
import joblib
import numpy as np
from flask import Flask, request, render_template_string
from tensorflow.keras.models import load_model
!pip install pyngrok
from pyngrok import ngrok

# Set Authtoken ngrok (SESUAIKAN AUTH TOKEN)
ngrok.set_auth_token("2tTBESTAODURPjFw1ORx9ixJK4J_6bPteDVc2fthWC97GJY81")

app = Flask(__name__)

# Load model dan vectorizer
model = load_model('model_phishing.h5')
vectorizer = joblib.load('tfidf_vectorizer.pkl')

def predict_phishing(url):
    url_vec = vectorizer.transform([url]).toarray()
    prediction = model.predict(url_vec)
    threshold = 0.5
    return 'Phishing' if prediction > threshold else 'Legitimate'

@app.route("/")
def home():
    html = """
    <!DOCTYPE html>
    <html lang="id">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Dashboard - Phishing URL Detector</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />
        <style>
            body { background-color: #FFF9C4; }
            .text-justify { text-align: justify; }
            .btn-feature { margin-top: 1rem; }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-light bg-light shadow-sm py-3">
            <div class="container">
                <span class="navbar-brand mb-0 h1">Phishing URL Detector</span>
            </div>
        </nav>
        <div class="container min-vh-100 d-flex flex-column justify-content-center align-items-center py-5">
            <h1 class="text-primary fw-bold mb-4">Selamat Datang!</h1>
            <p class="text-muted fs-5 mb-4 text-justify" style="max-width: 700px;">
                Website ini membantu Anda memeriksa apakah sebuah URL bersifat phishing atau legitimate dengan menggunakan model Neural Network yang telah dilatih.
            </p>
            <a href="/check" class="btn btn-primary btn-lg rounded-pill btn-feature">Periksa URL</a>
            <a href="/about_nn" class="btn btn-secondary btn-lg rounded-pill btn-feature">Tentang Neural Network</a>
            <a href="/about_phishing" class="btn btn-secondary btn-lg rounded-pill btn-feature">Tentang Phishing</a>
        </div>
        <footer class="bg-light text-center py-3 fw-bold">
            <p class="mb-0">
                &copy; 𖥦  ꗃ ˓  ℰ𝑙𝑠𝑎 ℳ𝑎𝑢𝑙𝑖𝑛𝑎 𝒮𝑎𝑟𝑖   ໋֢ 𖥻 ⋆<br>
            𝗘𝗹𝗲𝗰𝘁𝗿𝗶𝗰𝗮𝗹 𝗘𝗻𝗴𝗶𝗻𝗲𝗲𝗿𝗶𝗻𝗴 — 𝗨𝗻𝗶𝘃𝗲𝗿𝘀𝗶𝘁𝗮𝘀 𝗣𝗲𝗺𝗯𝗮𝗻𝗴𝘂𝗻𝗮𝗻 𝗡𝗮𝘀𝗶𝗼𝗻𝗮𝗹 𝗩𝗲𝘁𝗲𝗿𝗮𝗻 𝗝𝗮𝗸𝗮𝗿𝘁𝗮<br>
            𝟮𝟭𝟭𝟬𝟯𝟭𝟰𝟬𝟵𝟯@𝗺𝗮𝗵𝗮𝘀𝗶𝘀𝘄𝗮.𝘂𝗽𝗻𝘃𝗷.𝗮𝗰.𝗶𝗱
            </p>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    </body>
    </html>
    """
    return render_template_string(html)

@app.route("/check", methods=["GET", "POST"])
def check():
    message = None
    explanation = None
    warning = None
    user_url = ""
    if request.method == "POST":
        user_url = request.form.get("url", "")
        if user_url:
            result = predict_phishing(user_url)
            if result == "Phishing":
                message = "URL yang Anda masukkan terdeteksi sebagai Phishing."
                explanation = (
                    "Deteksi phishing ini berdasarkan analisis karakteristik dan pola URL yang mencurigakan "
                    "menggunakan model Neural Network kami."
                )
                warning = "PERINGATAN: Harap berhati-hati dan jangan klik tautan ini untuk menghindari potensi penipuan atau malware."
            else:
                message = "URL yang Anda masukkan terdeteksi sebagai Legitimate."
                explanation = (
                    "Meskipun URL ini tampak legitimate, kami tetap menyarankan Anda untuk selalu berhati-hati "
                    "dalam mengakses tautan di internet."
                )
                warning = "PERHATIAN: Tetap waspada dan pastikan keamanan sebelum mengunjungi tautan."
    html = """
    <!DOCTYPE html>
    <html lang="id">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Cek URL - Phishing Detector</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet" />
        <style>
            body { background-color:#F8BBD0; }
            .btn-back { font-size: 1.5rem; margin-bottom: 1rem; }
            .max-w-600 { max-width: 600px; }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-light bg-light shadow-sm">
            <div class="container d-flex justify-content-between align-items-center">
                <a href="/" class="btn btn-outline-primary btn-back" title="Back to Home">
                    <i class="fa fa-arrow-left"></i>
                </a>
                <span class="navbar-brand">Periksa URL</span>
                <div style="width:42px;"></div>
            </div>
        </nav>

        <main class="container min-vh-100 d-flex flex-column justify-content-center align-items-center py-4">
            <form method="POST" class="w-100 max-w-600 shadow-lg bg-white p-4 rounded-4">
                <div class="mb-4">
                    <input
                        type="url"
                        name="url"
                        class="form-control form-control-lg"
                        placeholder="Masukkan URL (contoh: https://example.com)"
                        aria-label="Input URL"
                        pattern="(https?://|www\\.)\\S+"
                        title="Masukkan URL yang valid (contoh: https://example.com)"
                        value="{{ user_url }}"
                        required
                    />
                </div>
                <button type="submit" class="btn btn-primary btn-lg w-100 rounded-pill">
                    <i class="fa fa-search"></i> Periksa
                </button>
            </form>

            {% if message %}
            <div class="alert {% if 'Phishing' in message %}alert-danger{% else %}alert-success{% endif %} mt-4 max-w-600 text-center shadow rounded-4">
                <h4>{{ message }}</h4>
                <p>{{ explanation }}</p>
                <strong>{{ warning }}</strong>
            </div>
            {% endif %}
        </main>

        <footer class="bg-light text-center py-3 fw-bold">
            <p class="mb-0">&copy; 𖥦  ꗃ ˓  ℰ𝑙𝑠𝑎 ℳ𝑎𝑢𝑙𝑖𝑛𝑎 𝒮𝑎𝑟𝑖   ໋֢ 𖥻 ⋆<br>
            𝗘𝗹𝗲𝗰𝘁𝗿𝗶𝗰𝗮𝗹 𝗘𝗻𝗴𝗶𝗻𝗲𝗲𝗿𝗶𝗻𝗴 — 𝗨𝗻𝗶𝘃𝗲𝗿𝘀𝗶𝘁𝗮𝘀 𝗣𝗲𝗺𝗯𝗮𝗻𝗴𝘂𝗻𝗮𝗻 𝗡𝗮𝘀𝗶𝗼𝗻𝗮𝗹 𝗩𝗲𝘁𝗲𝗿𝗮𝗻 𝗝𝗮𝗸𝗮𝗿𝘁𝗮<br>
            𝟮𝟭𝟭𝟬𝟯𝟭𝟰𝟬𝟵𝟯@𝗺𝗮𝗵𝗮𝘀𝗶𝘀𝘄𝗮.𝘂𝗽𝗻𝘃𝗷.𝗮𝗰.𝗶𝗱</p>
        </footer>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    </body>
    </html>
    """
    return render_template_string(
        html,
        message=message,
        explanation=explanation,
        warning=warning,
        user_url=user_url,
    )

@app.route("/about_nn")
def about_nn():
    html = """
    <!DOCTYPE html>
    <html lang="id">
    <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Tentang Neural Network</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />
    <style>
        body { background-color: #FFF9C4; }
        .content { max-width: 700px; margin: 2rem auto; }
    </style>
    </head>
    <body>
    <nav class="navbar navbar-light bg-light shadow-sm py-3">
        <div class="container">
            <a href="/" class="btn btn-outline-primary"><i class="fa fa-arrow-left"></i> Kembali</a>
            <span class="navbar-brand ms-3">Tentang Neural Network</span>
        </div>
    </nav>

    <div class="content">
        <h2>Neural Network</h2>
        <p class="text-justify">Neural Network adalah model machine learning yang meniru cara kerja otak manusia dalam mengenali pola dan hubungan data. Model ini berguna untuk mengklasifikasikan URL sebagai phishing atau legitimate berdasarkan fitur-fitur yang dipelajari selama pelatihan.</p>
    </div>

    <footer class="bg-light text-center py-3 fw-bold">
        <p class="mb-0">&copy; 𖥦  ꗃ ˓  ℰ𝑙𝑠𝑎 ℳ𝑎𝑢𝑙𝑖𝑛𝑎 𝒮𝑎𝑟𝑖   ໋֢ 𖥻 ⋆<br>
            𝗘𝗹𝗲𝗰𝘁𝗿𝗶𝗰𝗮𝗹 𝗘𝗻𝗴𝗶𝗻𝗲𝗲𝗿𝗶𝗻𝗴 — 𝗨𝗻𝗶𝘃𝗲𝗿𝘀𝗶𝘁𝗮𝘀 𝗣𝗲𝗺𝗯𝗮𝗻𝗴𝘂𝗻𝗮𝗻 𝗡𝗮𝘀𝗶𝗼𝗻𝗮𝗹 𝗩𝗲𝘁𝗲𝗿𝗮𝗻 𝗝𝗮𝗸𝗮𝗿𝘁𝗮<br>
            𝟮𝟭𝟭𝟬𝟯𝟭𝟰𝟬𝟵𝟯@𝗺𝗮𝗵𝗮𝘀𝗶𝘀𝘄𝗮.𝘂𝗽𝗻𝘃𝗷.𝗮𝗰.𝗶𝗱</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    </body>
    </html>
    """
    return render_template_string(html)

@app.route("/about_phishing")
def about_phishing():
    html = """
    <!DOCTYPE html>
    <html lang="id">
    <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Tentang Phishing</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />
    <style>
        body { background-color: #FFF9C4; }
        .content { max-width: 700px; margin: 2rem auto; }
    </style>
    </head>
    <body>
    <nav class="navbar navbar-light bg-light shadow-sm py-3">
        <div class="container">
            <a href="/" class="btn btn-outline-primary"><i class="fa fa-arrow-left"></i> Kembali</a>
            <span class="navbar-brand ms-3">Tentang Phishing</span>
        </div>
    </nav>

    <div class="content">
        <h2>Phishing</h2>
        <p class="text-justify">Phishing adalah metode penipuan online di mana pelaku mencoba memperoleh informasi pribadi pengguna dengan menyamar sebagai entitas tepercaya melalui tautan palsu. Situs phishing seringkali terlihat sangat mirip dengan situs asli untuk mengelabui korban.</p>
    </div>

    <footer class="bg-light text-center py-3 fw-bold">
        <p class="mb-0">&copy; 𖥦  ꗃ ˓  ℰ𝑙𝑠𝑎 ℳ𝑎𝑢𝑙𝑖𝑛𝑎 𝒮𝑎𝑟𝑖   ໋֢ 𖥻 ⋆<br>
            𝗘𝗹𝗲𝗰𝘁𝗿𝗶𝗰𝗮𝗹 𝗘𝗻𝗴𝗶𝗻𝗲𝗲𝗿𝗶𝗻𝗴 — 𝗨𝗻𝗶𝘃𝗲𝗿𝘀𝗶𝘁𝗮𝘀 𝗣𝗲𝗺𝗯𝗮𝗻𝗴𝘂𝗻𝗮𝗻 𝗡𝗮𝘀𝗶𝗼𝗻𝗮𝗹 𝗩𝗲𝘁𝗲𝗿𝗮𝗻 𝗝𝗮𝗸𝗮𝗿𝘁𝗮<br>
            𝟮𝟭𝟭𝟬𝟯𝟭𝟰𝟬𝟵𝟯@𝗺𝗮𝗵𝗮𝘀𝗶𝘀𝘄𝗮.𝘂𝗽𝗻𝘃𝗷.𝗮𝗰.𝗶𝗱</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    </body>
    </html>
    """
    return render_template_string(html)

if __name__ == "__main__":
    public_url = ngrok.connect(5000)
    print(f" * Ngrok tunnel available at: {public_url}")
    app.run(debug=True, use_reloader=False)